@host = http://localhost:3000

GET {{host}}/api/autores

###
POST {{host}}/api/autores
Content-Type: application/json

{
  "nombre": "paco",
  "email": "paco@example.com",
  "imagen": 
  }


###
GET {{host}}/api/autores/1